sudo: required

language: cpp # we run all tests in docker container so this can be anything

services:
  - docker

before_install:
  - make -C tai_mux docker-image

script:
  - TAI_DOCKER_CMD='make test' make -C tai_mux cmd
